 import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.sqldelight)
}

val appVersion = "1.3.2"

val generateAppVersion by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/appversion/commonMain/kotlin")
    val version = appVersion
    outputs.dir(outputDir)
    doLast {
        val dir = outputDir.get().asFile
        dir.mkdirs()
        dir.resolve("AppVersion.kt").writeText(
            """package com.aracem.joyufy
|
|object AppVersion {
|    const val NAME = "$version"
|}
|""".trimMargin()
        )
    }
}

val generateDriveConfig by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/driveconfig/desktopMain/kotlin")
    val clientId = providers.environmentVariable("GOOGLE_DRIVE_CLIENT_ID").orElse("")
    val clientSecret = providers.environmentVariable("GOOGLE_DRIVE_CLIENT_SECRET").orElse("")
    outputs.dir(outputDir)
    // Re-run whenever the secrets change so a build with new credentials regenerates the file.
    inputs.property("clientId", clientId)
    inputs.property("clientSecret", clientSecret)
    doLast {
        val dir = outputDir.get().asFile
        dir.mkdirs()
        dir.resolve("GoogleDriveConfig.kt").writeText(
            """package com.aracem.joyufy.data.cloud
|
|// Auto-generated by the `generateDriveConfig` Gradle task from the
|// GOOGLE_DRIVE_CLIENT_ID / GOOGLE_DRIVE_CLIENT_SECRET env vars.
|// Do not edit by hand — set the env vars in your shell or CI secrets.
|object GoogleDriveConfig {
|    const val CLIENT_ID = "${clientId.get()}"
|    const val CLIENT_SECRET = "${clientSecret.get()}"
|
|    val isConfigured: Boolean
|        get() = CLIENT_ID.isNotEmpty() && CLIENT_SECRET.isNotEmpty()
|}
|""".trimMargin()
        )
    }
}

kotlin {
    jvm("desktop")

    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    sourceSets {
        val desktopMain by getting {
            kotlin.srcDir(generateDriveConfig.map { it.outputs.files })
        }

        commonMain {
            kotlin.srcDir(generateAppVersion.map { it.outputs.files })
        }

        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.materialIconsExtended)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(compose.components.uiToolingPreview)

            // SQLDelight
            implementation(libs.sqldelight.runtime)
            implementation(libs.sqldelight.coroutines)

            // Koin
            implementation(libs.koin.core)
            implementation(libs.koin.compose)

            // Kotlinx
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.datetime)
        }

        desktopMain.dependencies {
            implementation(compose.desktop.currentOs)

            // SQLDelight Desktop driver
            implementation(libs.sqldelight.driver.sqlite)
            implementation(libs.sqlite.jdbc)

            // Main dispatcher for desktop (Swing event loop)
            implementation(libs.kotlinx.coroutines.swing)

            // Ktor (Google Drive REST API)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.cio)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)
        }

        val desktopTest by getting {
            dependencies {
                implementation(kotlin("test"))
                implementation(libs.kotlinx.coroutines.test)
                implementation(libs.sqldelight.driver.sqlite)
                implementation(libs.sqlite.jdbc)
            }
        }
    }
}

sqldelight {
    databases {
        create("JoyufyDatabase") {
            packageName.set("com.aracem.joyufy.db")
        }
    }
}

compose.desktop {
    application {
        mainClass = "com.aracem.joyufy.MainKt"

        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "Joyufy"
            packageVersion = appVersion
            modules("java.sql", "java.naming")
            description = "Control personal de finanzas"
            copyright = "© 2026 Aracem"
            vendor = "Aracem"

            macOS {
                bundleID = "com.aracem.joyufy"
                iconFile.set(project.file("src/desktopMain/resources/icon.icns"))
            }
            windows {
                iconFile.set(project.file("src/desktopMain/resources/icon.ico"))
                upgradeUuid = "a3f1e2d4-7b8c-4f5a-9e6d-1c2b3a4d5e6f"
                menuGroup = "Joyufy"
                perUserInstall = true
            }
            linux {
                iconFile.set(project.file("src/desktopMain/resources/icon.png"))
                packageName = "joyufy"
            }
        }
    }
}
