package com.aracem.joyufy.ui.strings

object StringsEn : Strings {
    // Navigation
    override val goBack = "Go back"
    override val sidebarDashboard = "Dashboard"
    override val sidebarTransactions = "Transactions"
    override val sidebarSettings = "Settings"
    override val sidebarCollapse = "Collapse sidebar"
    override val sidebarExpand = "Expand sidebar"
    override val sidebarReorderEnter = "Reorder accounts"
    override val sidebarReorderExit = "Exit reorder mode"
    override val sidebarReorder = "Reorder"
    override val sidebarNewAccount = "New account"
    override val sidebarQuickAdd = "Add transaction"
    override val sidebarDarkMode = "Light mode"
    override val sidebarLightMode = "Dark mode"

    // Common actions
    override val cancel = "Cancel"
    override val delete = "Delete"
    override val edit = "Edit"
    override val saveChanges = "Save changes"
    override val close = "Close"
    override val download = "Download"
    override val undo = "Undo"
    override val selectAll = "Select all"
    override val clearSelection = "Clear selection"

    // Dashboard
    override val totalWealth = "Total wealth"
    override val noAccountsYet = "No accounts yet"
    override val addFirstAccount = "Create the first account and the dashboard will start tracking your wealth automatically"
    override val createBankAccount = "Bank account"
    override val createInvestmentAccount = "Investment account"
    override val createCashAccount = "Cash account"
    override val evolution = "Evolution"
    override val changeView = "Change view"
    override val chartModeArea = "Area"
    override val chartModeBars = "Bars"
    override val chartVisibility = "Visible data"
    override val chartVisibilityAll = "All"
    override val chartVisibilityLiquid = "Liquid only"
    override val chartVisibilityInvestments = "Investments only"
    override val chartVisibilityCustom = "Custom"
    override val composition = "Composition"
    override val compositionEmpty = "No positive balances yet"
    override val missingSnapshotTitle = "Weekly investment update pending"
    override val missingSnapshotSubtitle = "Update stale investment accounts before closing the week"
    override val missingSnapshotLastValue = "Last value: %s"
    override val missingSnapshotNever = "Never updated"
    override val dashboardActions = "Needs review"
    override val uncategorized = "Uncategorized"
    override val pendingSnapshots = "Pending snapshots"
    override val negativeBalances = "Negative balances"
    override val hiddenSeries = "Hidden series"
    override val periodComparison = "Period comparison"
    override val vsPreviousMonth = "vs previous month"
    override val analysis = "Analysis"
    override val collapse = "Collapse"
    override val expand = "Expand"

    // Monthly summary
    override val currentMonth = "This month"
    override val income = "Income"
    override val expenses = "Expenses"
    override val investment = "Investment"
    override val net = "Net"
    override val topExpenses = "Top expenses"
    override val monthCurrent = "Current month"

    // Annual summary
    override val currentYear = "This year"
    override val yearAll = "All"
    override val yearPrevious = "Previous year"
    override val yearNext = "Next year"

    // Chart ranges
    override val chartWeek = "1W"
    override val chartMonth = "1M"
    override val chartThreeMonths = "3M"
    override val chartSixMonths = "6M"
    override val chartYtd = "YTD"
    override val chartYear = "1Y"
    override val rangeOneWeek = "in the last week"
    override val rangeOneMonth = "in the last month"
    override val rangeThreeMonths = "in the last 3 months"
    override val rangeSixMonths = "in the last 6 months"
    override val rangeYtd = "year-to-date"
    override val rangeOneYear = "in the last year"
    override val rangeAll = "since the beginning"

    // Account detail
    override val confirmTypeChangeTitle = "Change account type?"
    override val confirmTypeChangeBody = "This is a destructive operation and cannot be undone."
    override val confirmTypeChangeBankToInvestment = "Switching to Investment will delete %1\$d transactions and replace them with a single snapshot for this week with the current balance."
    override val confirmTypeChangeInvestmentToBank = "Switching away from Investment will delete %1\$d weekly snapshots. Any transactions on this account will be kept."
    override val confirmTypeChangeContinue = "Change type"
    override val editAccount = "Edit account"
    override val updateValue = "Update value"
    override val addTransaction = "Add transaction"
    override val currentBalance = "Current balance"
    override val transactions = "Transactions"
    override val monthSubtotal = "Month subtotal"
    override val runningBalance = "Running balance"
    override val noTransactions = "No transactions yet"
    override val noTransactionsHint = "Press \"Add transaction\" to record the first one"
    override val noSearchResults = "No results"
    override val noSearchResultsHint = "Try changing or clearing the filters"
    override val weeklyValue = "Weekly market value"
    override val noWeeklyRecords = "No weekly records"
    override val noWeeklyRecordsHint = "Press \"Update value\" to add the first one"
    override val editValue = "Edit value"
    override val weekCurrent = "Current week — "
    override val week = "Week"

    // Filters
    override val clearFilters = "Clear"
    override val searchDescriptionCategory = "Search by description or category…"
    override val transactionType = "Type"
    override val dateFrom = "From"
    override val dateTo = "To"
    override val amountMin = "Min"
    override val amountMax = "Max"
    override val transfersOnly = "Transfers only"
    override val transferOut = "Transfer out →"
    override val transferIn = "Transfer in ←"

    // Add/Edit transaction
    override val editTransaction = "Edit transaction"
    override val newTransaction = "New transaction"
    override val amountEur = "Amount (€)"
    override val dateFormat = "Date (dd/MM/yyyy)"
    override val categoryOptional = "Category (optional)"
    override val descriptionOptional = "Description (optional)"
    override val destinationAccount = "Destination account"
    override val selectDate = "Select date"
    override val selectDestinationAccount = "Select a destination account to continue"
    override val noDestinationAccounts = "Create another account before recording a transfer"
    override val placeholderAmount = "0.00"
    override val buttonTransfer = "Transfer"
    override val buttonAdd = "Add"
    override val amountError = "Enter a valid amount"
    override val dateError = "Use the format dd/MM/yyyy"
    override val transactionTemplates = "Templates"
    override val templateSalary = "Salary"
    override val templateGroceries = "Groceries"
    override val templateRent = "Rent"
    override val templateSubscription = "Subscription"
    override val templateInvestmentTransfer = "Investment deposit"

    // Add/Edit snapshot
    override val totalValueEur = "Total value (€)"
    override val valueError = "Enter a valid value"
    override val save = "Save"

    // Create account
    override val newAccount = "New account"
    override val createAccount = "Create account"
    override val name = "Name"
    override val typeLabel = "Type"
    override val color = "Color"
    override val placeholderName = "E.g.: Santander Bank"
    override val customColor = "Custom color"
    override val placeholderColor = "#7B6EF6"
    override val initialBalanceOptional = "Initial balance (optional)"
    override val bankOrPlatform = "Bank or platform"
    override val moreOptions = "More options"

    // Account types
    override val accountTypeBank = "Bank"
    override val accountTypeInvestment = "Investment"
    override val accountTypeCash = "Cash"

    // Transaction types
    override val transactionIncome = "Income"
    override val transactionExpense = "Expense"
    override val transactionTransfer = "Transfer"

    // Transaction ledger
    override val transactionLedger = "Transaction ledger"
    override val ledgerSubtitle = "%d transactions across all accounts"
    override val ledgerReviewInbox = "Review inbox"
    override val ledgerAll = "All"
    override val ledgerDataQuality = "Data quality"
    override val ledgerSearchPlaceholder = "Search transactions, accounts, categories…"
    override val ledgerAllAccounts = "All accounts"
    override val ledgerAllTypes = "All types"
    override val ledgerSelectedCount = "%d selected"
    override val ledgerBulkCategory = "Category"
    override val ledgerApplyCategory = "Apply category"
    override val ledgerMoveToAccount = "Move account"
    override val ledgerMarkReviewed = "Mark reviewed"
    override val ledgerDeleteSelected = "Delete"
    override val ledgerDeletedTransactions = "%d transactions deleted"
    override val ledgerRestoredTransactions = "%d transactions restored"
    override val ledgerUpdatedTransactions = "%d transactions updated"
    override val ledgerNoTransactions = "No transactions match these filters"
    override val ledgerDataQualityTitle = "Data quality"
    override val ledgerMissingCategories = "Missing categories"
    override val ledgerEmptyDescriptions = "Empty descriptions"
    override val ledgerPossibleDuplicates = "Possible duplicates"
    override val ledgerBrokenTransfers = "Broken transfers"
    override val ledgerUnusualAmounts = "Unusual amounts"
    override val ledgerStaleAccounts = "Stale accounts"
    override val ledgerStaleSnapshots = "Stale snapshots"
    override val ledgerImportedDrafts = "Imported drafts"
    override val ledgerImportedDraft = "Imported draft"
    override val ledgerMissingCategory = "Missing category"
    override val ledgerEmptyDescription = "Empty description"
    override val ledgerDuplicateHint = "Duplicate group: %d"
    override val ledgerBrokenTransfer = "Broken transfer"
    override val ledgerUnusualAmount = "Unusual amount"
    override val ledgerNoDescription = "No description"

    // Settings
    override val settings = "Settings"
    override val appearance = "Appearance"
    override val darkMode = "Dark mode"
    override val lightMode = "Light mode"
    override val themeDescription = "Switch between dark and light theme"
    override val data = "Data"
    override val exportBackup = "Export backup"
    override val importBackup = "Import backup"
    override val exportData = "Export data"
    override val importData = "Import data"
    override val accounts = "Accounts"
    override val noAccounts = "No accounts"
    override val dangerZone = "Danger zone"
    override val dangerZoneDescription = "Destructive actions are isolated here and require confirmation."
    override val deleteAllData = "Delete all data"
    override val language = "Language"
    override val settingsTabGeneral = "General"
    override val settingsTabAccounts = "Accounts"
    override val settingsTabData = "Data"
    override val settingsTabCloud = "Cloud"
    override val settingsTabAbout = "About"

    // Cloud sync
    override val cloudSync = "Cloud sync"
    override val cloudStatusConnected = "Connected"
    override val cloudStatusDisconnected = "Disconnected"
    override val cloudStatusConnecting = "Connecting"
    override val cloudStatusUploading = "Uploading"
    override val cloudStatusDownloading = "Downloading"
    override val cloudStatusConflict = "Conflict pending"
    override val cloudStatusReady = "Ready"
    override val connectDrive = "Connect Google Drive"
    override val disconnectDrive = "Disconnect"
    override val driveConnected = "Connected as %s"
    override val uploadNow = "Upload now"
    override val restoreFromDrive = "Restore from Drive"
    override val autoSync = "Auto-sync"
    override val manualSync = "Manual sync"
    override val autoSyncDescription = "Upload on close, download on launch"
    override val lastSync = "Last sync: %s"
    override val lastSyncNever = "Never synced"
    override val syncSuccess = "Synced with Google Drive"
    override val syncError = "Sync failed"
    override val syncing = "Syncing…"
    override val syncingToDrive = "Syncing to Google Drive…"
    override val confirmRestoreFromDrive = "Restore from Drive?"
    override val confirmRestoreFromDriveText = "All current data will be replaced with the Drive backup. This action cannot be undone."
    override val cloudDiffTitle = "Cloud backup differs from local"
    override val cloudDiffSubtitle = "Your Google Drive backup is different from your local data. Choose which one to keep."
    override val cloudDiffAccounts = "Accounts"
    override val cloudDiffTransactions = "Transactions"
    override val cloudDiffSnapshots = "Investment snapshots"
    override val cloudDiffEntity = "Data"
    override val cloudDiffAdded = "added"
    override val cloudDiffRemoved = "removed"
    override val cloudDiffModified = "modified"
    override val cloudBackupTimestamp = "Cloud backup: %s"
    override val localDataCurrent = "Local data: current device state"
    override val keepLocal = "Keep local"
    override val useCloud = "Use cloud"

    // Command palette
    override val commandPalette = "Command palette"
    override val commandPalettePlaceholder = "Search actions or accounts…"
    override val commandPaletteNoResults = "No matching actions"
    override val commandOpenAccount = "Open %s"
    override val commandNewTransaction = "New transaction"
    override val commandUpdateSnapshot = "Update investment value"
    override val commandFocusSearch = "Search transactions"
    override val commandReviewUncategorized = "Review uncategorized"

    // Import preview
    override val importPreviewTitle = "Preview backup import"
    override val importPreviewSubtitle = "Review the differences before replacing local data with this file."
    override val importPreviewBackupTimestamp = "File backup: %s"
    override val importPreviewNoChanges = "No differences detected against local data"
    override val importPreviewRestore = "Restore file"

    // CSV import
    override val csvImportTitle = "Import bank statement"
    override val csvImportSubtitle = "Supports CSV, TSV, OFX, and ING text exports. Duplicates are blocked before import."
    override val csvDefaultAccount = "Default account"
    override val csvImportRows = "%d rows"
    override val csvImportValid = "%d valid"
    override val csvImportErrors = "%d errors"
    override val csvImportDuplicates = "%d duplicates"
    override val csvImportInvalidField = "Invalid %s"
    override val csvImportDuplicateHint = "Duplicate: will not be imported"
    override val csvImportCommit = "Import %d"
    override val csvImportSuccess = "%d transactions imported as drafts"

    // Undo feedback
    override val snapshotDeleted = "Snapshot deleted"
    override val accountDeleted = "%s deleted"
    override val accountArchived = "%s archived"
    override val accountRestored = "%s restored"

    // Confirm dialogs
    override val confirmDeleteTransaction = "Delete transaction?"
    override val confirmDeleteTransactionText = "This action cannot be undone."
    override val confirmDeleteSnapshot = "Delete weekly record?"
    override val confirmDeleteSnapshotText = "This action cannot be undone."
    override val confirmDeleteAccount = "Delete account?"
    override val confirmDeleteAccountText = "The account and all its transactions and snapshots will be permanently deleted. This action cannot be undone."
    override val confirmDeleteAll = "Delete all data?"
    override val confirmDeleteAllText = "All accounts, transactions and snapshots will be deleted. The application will be empty. This action cannot be undone."
    override val confirmDeleteAllTypedInstruction = "Type %s to permanently delete all local data."
    override val confirmDeleteAllInputLabel = "Confirmation"
    override val confirmDeleteAllPhrase = "DELETE"
    override val deleteAll = "Delete all"
    override val confirmRestoreBackup = "Restore backup?"
    override val confirmRestoreBackupText = "All current data will be deleted and replaced with the file contents. This action cannot be undone."
    override val restore = "Restore"
}
