package com.aracem.joyufy.ui.strings

import androidx.compose.runtime.compositionLocalOf

data class Strings(
    // Navigation
    val goBack: String,
    val sidebarDashboard: String,
    val sidebarTransactions: String,
    val sidebarSettings: String,
    val sidebarCollapse: String,
    val sidebarExpand: String,
    val sidebarReorderEnter: String,
    val sidebarReorderExit: String,
    val sidebarReorder: String,
    val sidebarNewAccount: String,
    val sidebarQuickAdd: String,
    val sidebarDarkMode: String,
    val sidebarLightMode: String,

    // Common actions
    val cancel: String,
    val delete: String,
    val edit: String,
    val saveChanges: String,
    val close: String,
    val download: String,
    val undo: String,
    val selectAll: String,
    val clearSelection: String,

    // Dashboard
    val totalWealth: String,
    val noAccountsYet: String,
    val addFirstAccount: String,
    val createBankAccount: String,
    val createInvestmentAccount: String,
    val createCashAccount: String,
    val evolution: String,
    val changeView: String,
    val chartModeArea: String,
    val chartModeBars: String,
    val chartVisibility: String,
    val chartVisibilityAll: String,
    val chartVisibilityLiquid: String,
    val chartVisibilityInvestments: String,
    val chartVisibilityCustom: String,
    val composition: String,
    val compositionEmpty: String,
    val missingSnapshotTitle: String,
    val missingSnapshotSubtitle: String,
    val missingSnapshotLastValue: String,
    val missingSnapshotNever: String,
    val dashboardActions: String,
    val uncategorized: String,
    val pendingSnapshots: String,
    val negativeBalances: String,
    val hiddenSeries: String,
    val periodComparison: String,
    val vsPreviousMonth: String,
    val analysis: String,
    val collapse: String,
    val expand: String,

    // Monthly summary
    val currentMonth: String,
    val income: String,
    val expenses: String,
    val investment: String,
    val net: String,
    val topExpenses: String,
    val monthCurrent: String,

    // Annual summary
    val currentYear: String,
    val yearAll: String,
    val yearPrevious: String,
    val yearNext: String,

    // Chart ranges
    val chartWeek: String,
    val chartMonth: String,
    val chartThreeMonths: String,
    val chartSixMonths: String,
    val chartYtd: String,
    val chartYear: String,
    val rangeOneWeek: String,
    val rangeOneMonth: String,
    val rangeThreeMonths: String,
    val rangeSixMonths: String,
    val rangeYtd: String,
    val rangeOneYear: String,
    val rangeAll: String,

    // Account type change (destructive)
    val confirmTypeChangeTitle: String,
    val confirmTypeChangeBody: String,
    val confirmTypeChangeBankToInvestment: String,
    val confirmTypeChangeInvestmentToBank: String,
    val confirmTypeChangeContinue: String,

    // Account detail
    val editAccount: String,
    val updateValue: String,
    val addTransaction: String,
    val currentBalance: String,
    val transactions: String,
    val monthSubtotal: String,
    val runningBalance: String,
    val noTransactions: String,
    val noTransactionsHint: String,
    val noSearchResults: String,
    val noSearchResultsHint: String,
    val weeklyValue: String,
    val noWeeklyRecords: String,
    val noWeeklyRecordsHint: String,
    val editValue: String,
    val weekCurrent: String,
    val week: String,

    // Filters
    val clearFilters: String,
    val searchDescriptionCategory: String,
    val transactionType: String,
    val dateFrom: String,
    val dateTo: String,
    val amountMin: String,
    val amountMax: String,
    val transfersOnly: String,
    val transferOut: String,
    val transferIn: String,

    // Add/Edit transaction
    val editTransaction: String,
    val newTransaction: String,
    val amountEur: String,
    val dateFormat: String,
    val categoryOptional: String,
    val descriptionOptional: String,
    val destinationAccount: String,
    val selectDate: String,
    val selectDestinationAccount: String,
    val noDestinationAccounts: String,
    val placeholderAmount: String,
    val buttonTransfer: String,
    val buttonAdd: String,
    val amountError: String,
    val dateError: String,
    val transactionTemplates: String,
    val templateSalary: String,
    val templateGroceries: String,
    val templateRent: String,
    val templateSubscription: String,
    val templateInvestmentTransfer: String,

    // Add/Edit snapshot
    val totalValueEur: String,
    val valueError: String,
    val save: String,

    // Create account
    val newAccount: String,
    val createAccount: String,
    val name: String,
    val typeLabel: String,
    val color: String,
    val placeholderName: String,
    val customColor: String,
    val placeholderColor: String,
    val initialBalanceOptional: String,
    val bankOrPlatform: String,
    val moreOptions: String,

    // Account types
    val accountTypeBank: String,
    val accountTypeInvestment: String,
    val accountTypeCash: String,

    // Transaction types
    val transactionIncome: String,
    val transactionExpense: String,
    val transactionTransfer: String,

    // Transaction ledger
    val transactionLedger: String,
    val ledgerSubtitle: String,
    val ledgerReviewInbox: String,
    val ledgerAll: String,
    val ledgerDataQuality: String,
    val ledgerSearchPlaceholder: String,
    val ledgerAllAccounts: String,
    val ledgerAllTypes: String,
    val ledgerSelectedCount: String,
    val ledgerBulkCategory: String,
    val ledgerApplyCategory: String,
    val ledgerDeleteSelected: String,
    val ledgerDeletedTransactions: String,
    val ledgerRestoredTransactions: String,
    val ledgerNoTransactions: String,
    val ledgerDataQualityTitle: String,
    val ledgerMissingCategories: String,
    val ledgerEmptyDescriptions: String,
    val ledgerPossibleDuplicates: String,
    val ledgerBrokenTransfers: String,
    val ledgerUnusualAmounts: String,
    val ledgerStaleAccounts: String,
    val ledgerStaleSnapshots: String,
    val ledgerImportedDrafts: String,
    val ledgerMissingCategory: String,
    val ledgerEmptyDescription: String,
    val ledgerDuplicateHint: String,
    val ledgerBrokenTransfer: String,
    val ledgerUnusualAmount: String,
    val ledgerNoDescription: String,

    // Settings
    val settings: String,
    val appearance: String,
    val darkMode: String,
    val lightMode: String,
    val themeDescription: String,
    val data: String,
    val exportBackup: String,
    val importBackup: String,
    val exportData: String,
    val importData: String,
    val accounts: String,
    val noAccounts: String,
    val dangerZone: String,
    val dangerZoneDescription: String,
    val deleteAllData: String,
    val language: String,
    val settingsTabGeneral: String,
    val settingsTabAccounts: String,
    val settingsTabData: String,
    val settingsTabCloud: String,
    val settingsTabAbout: String,

    // Cloud sync
    val cloudSync: String,
    val cloudStatusConnected: String,
    val cloudStatusDisconnected: String,
    val cloudStatusConnecting: String,
    val cloudStatusUploading: String,
    val cloudStatusDownloading: String,
    val cloudStatusConflict: String,
    val cloudStatusReady: String,
    val connectDrive: String,
    val disconnectDrive: String,
    val driveConnected: String,
    val uploadNow: String,
    val restoreFromDrive: String,
    val autoSync: String,
    val manualSync: String,
    val autoSyncDescription: String,
    val lastSync: String,
    val lastSyncNever: String,
    val syncSuccess: String,
    val syncError: String,
    val syncing: String,
    val syncingToDrive: String,
    val confirmRestoreFromDrive: String,
    val confirmRestoreFromDriveText: String,
    val cloudDiffTitle: String,
    val cloudDiffSubtitle: String,
    val cloudDiffAccounts: String,
    val cloudDiffTransactions: String,
    val cloudDiffSnapshots: String,
    val cloudDiffEntity: String,
    val cloudDiffAdded: String,
    val cloudDiffRemoved: String,
    val cloudDiffModified: String,
    val cloudBackupTimestamp: String,
    val localDataCurrent: String,
    val keepLocal: String,
    val useCloud: String,

    // Command palette
    val commandPalette: String,
    val commandPalettePlaceholder: String,
    val commandPaletteNoResults: String,
    val commandOpenAccount: String,
    val commandNewTransaction: String,
    val commandUpdateSnapshot: String,
    val commandFocusSearch: String,
    val commandReviewUncategorized: String,

    // Import preview
    val importPreviewTitle: String,
    val importPreviewSubtitle: String,
    val importPreviewBackupTimestamp: String,
    val importPreviewNoChanges: String,
    val importPreviewRestore: String,

    // Confirm dialogs
    val confirmDeleteTransaction: String,
    val confirmDeleteTransactionText: String,
    val confirmDeleteSnapshot: String,
    val confirmDeleteSnapshotText: String,
    val confirmDeleteAccount: String,
    val confirmDeleteAccountText: String,
    val confirmDeleteAll: String,
    val confirmDeleteAllText: String,
    val confirmDeleteAllTypedInstruction: String,
    val confirmDeleteAllInputLabel: String,
    val confirmDeleteAllPhrase: String,
    val deleteAll: String,
    val confirmRestoreBackup: String,
    val confirmRestoreBackupText: String,
    val restore: String,
)

val LocalStrings = compositionLocalOf<Strings> { StringsEn }
