package com.aracem.joyufy.ui.strings

val StringsEn = Strings(
    // Navigation
    goBack = "Go back",
    sidebarDashboard = "Dashboard",
    sidebarTransactions = "Transactions",
    sidebarSettings = "Settings",
    sidebarCollapse = "Collapse sidebar",
    sidebarExpand = "Expand sidebar",
    sidebarReorderEnter = "Reorder accounts",
    sidebarReorderExit = "Exit reorder mode",
    sidebarReorder = "Reorder",
    sidebarNewAccount = "New account",
    sidebarQuickAdd = "Add transaction",
    sidebarDarkMode = "Light mode",
    sidebarLightMode = "Dark mode",

    // Common actions
    cancel = "Cancel",
    delete = "Delete",
    edit = "Edit",
    saveChanges = "Save changes",
    close = "Close",
    download = "Download",
    undo = "Undo",
    selectAll = "Select all",
    clearSelection = "Clear selection",

    // Dashboard
    totalWealth = "Total wealth",
    noAccountsYet = "No accounts yet",
    addFirstAccount = "Create the first account and the dashboard will start tracking your wealth automatically",
    createBankAccount = "Bank account",
    createInvestmentAccount = "Investment account",
    createCashAccount = "Cash account",
    evolution = "Evolution",
    changeView = "Change view",
    chartModeArea = "Area",
    chartModeBars = "Bars",
    chartVisibility = "Visible data",
    chartVisibilityAll = "All",
    chartVisibilityLiquid = "Liquid only",
    chartVisibilityInvestments = "Investments only",
    chartVisibilityCustom = "Custom",
    composition = "Composition",
    compositionEmpty = "No positive balances yet",
    missingSnapshotTitle = "Weekly investment update pending",
    missingSnapshotSubtitle = "Update stale investment accounts before closing the week",
    missingSnapshotLastValue = "Last value: %s",
    missingSnapshotNever = "Never updated",
    dashboardActions = "Needs review",
    uncategorized = "Uncategorized",
    pendingSnapshots = "Pending snapshots",
    negativeBalances = "Negative balances",
    hiddenSeries = "Hidden series",
    periodComparison = "Period comparison",
    vsPreviousMonth = "vs previous month",
    analysis = "Analysis",
    collapse = "Collapse",
    expand = "Expand",

    // Monthly summary
    currentMonth = "This month",
    income = "Income",
    expenses = "Expenses",
    investment = "Investment",
    net = "Net",
    topExpenses = "Top expenses",
    monthCurrent = "Current month",

    // Annual summary
    currentYear = "This year",
    yearAll = "All",
    yearPrevious = "Previous year",
    yearNext = "Next year",

    // Chart ranges
    chartWeek = "1W",
    chartMonth = "1M",
    chartThreeMonths = "3M",
    chartSixMonths = "6M",
    chartYtd = "YTD",
    chartYear = "1Y",
    rangeOneWeek = "in the last week",
    rangeOneMonth = "in the last month",
    rangeThreeMonths = "in the last 3 months",
    rangeSixMonths = "in the last 6 months",
    rangeYtd = "year-to-date",
    rangeOneYear = "in the last year",
    rangeAll = "since the beginning",

    // Account detail
    confirmTypeChangeTitle = "Change account type?",
    confirmTypeChangeBody = "This is a destructive operation and cannot be undone.",
    confirmTypeChangeBankToInvestment = "Switching to Investment will delete %1\$d transactions and replace them with a single snapshot for this week with the current balance.",
    confirmTypeChangeInvestmentToBank = "Switching away from Investment will delete %1\$d weekly snapshots. Any transactions on this account will be kept.",
    confirmTypeChangeContinue = "Change type",
    editAccount = "Edit account",
    updateValue = "Update value",
    addTransaction = "Add transaction",
    currentBalance = "Current balance",
    transactions = "Transactions",
    monthSubtotal = "Month subtotal",
    runningBalance = "Running balance",
    noTransactions = "No transactions yet",
    noTransactionsHint = "Press \"Add transaction\" to record the first one",
    noSearchResults = "No results",
    noSearchResultsHint = "Try changing or clearing the filters",
    weeklyValue = "Weekly market value",
    noWeeklyRecords = "No weekly records",
    noWeeklyRecordsHint = "Press \"Update value\" to add the first one",
    editValue = "Edit value",
    weekCurrent = "Current week — ",
    week = "Week",

    // Filters
    clearFilters = "Clear",
    searchDescriptionCategory = "Search by description or category…",
    transactionType = "Type",
    dateFrom = "From",
    dateTo = "To",
    amountMin = "Min",
    amountMax = "Max",
    transfersOnly = "Transfers only",
    transferOut = "Transfer out →",
    transferIn = "Transfer in ←",

    // Add/Edit transaction
    editTransaction = "Edit transaction",
    newTransaction = "New transaction",
    amountEur = "Amount (€)",
    dateFormat = "Date (dd/MM/yyyy)",
    categoryOptional = "Category (optional)",
    descriptionOptional = "Description (optional)",
    destinationAccount = "Destination account",
    selectDate = "Select date",
    selectDestinationAccount = "Select a destination account to continue",
    noDestinationAccounts = "Create another account before recording a transfer",
    placeholderAmount = "0.00",
    buttonTransfer = "Transfer",
    buttonAdd = "Add",
    amountError = "Enter a valid amount",
    dateError = "Use the format dd/MM/yyyy",
    transactionTemplates = "Templates",
    templateSalary = "Salary",
    templateGroceries = "Groceries",
    templateRent = "Rent",
    templateSubscription = "Subscription",
    templateInvestmentTransfer = "Investment deposit",

    // Add/Edit snapshot
    totalValueEur = "Total value (€)",
    valueError = "Enter a valid value",
    save = "Save",

    // Create account
    newAccount = "New account",
    createAccount = "Create account",
    name = "Name",
    typeLabel = "Type",
    color = "Color",
    placeholderName = "E.g.: Santander Bank",
    customColor = "Custom color",
    placeholderColor = "#7B6EF6",
    initialBalanceOptional = "Initial balance (optional)",
    bankOrPlatform = "Bank or platform",
    moreOptions = "More options",

    // Account types
    accountTypeBank = "Bank",
    accountTypeInvestment = "Investment",
    accountTypeCash = "Cash",

    // Transaction types
    transactionIncome = "Income",
    transactionExpense = "Expense",
    transactionTransfer = "Transfer",

    // Transaction ledger
    transactionLedger = "Transaction ledger",
    ledgerSubtitle = "%d transactions across all accounts",
    ledgerReviewInbox = "Review inbox",
    ledgerAll = "All",
    ledgerDataQuality = "Data quality",
    ledgerSearchPlaceholder = "Search transactions, accounts, categories…",
    ledgerAllAccounts = "All accounts",
    ledgerAllTypes = "All types",
    ledgerSelectedCount = "%d selected",
    ledgerBulkCategory = "Category",
    ledgerApplyCategory = "Apply category",
    ledgerDeleteSelected = "Delete",
    ledgerDeletedTransactions = "%d transactions deleted",
    ledgerRestoredTransactions = "%d transactions restored",
    ledgerNoTransactions = "No transactions match these filters",
    ledgerDataQualityTitle = "Data quality",
    ledgerMissingCategories = "Missing categories",
    ledgerEmptyDescriptions = "Empty descriptions",
    ledgerPossibleDuplicates = "Possible duplicates",
    ledgerBrokenTransfers = "Broken transfers",
    ledgerUnusualAmounts = "Unusual amounts",
    ledgerStaleAccounts = "Stale accounts",
    ledgerStaleSnapshots = "Stale snapshots",
    ledgerImportedDrafts = "Imported drafts",
    ledgerMissingCategory = "Missing category",
    ledgerEmptyDescription = "Empty description",
    ledgerDuplicateHint = "Duplicate group: %d",
    ledgerBrokenTransfer = "Broken transfer",
    ledgerUnusualAmount = "Unusual amount",
    ledgerNoDescription = "No description",

    // Settings
    settings = "Settings",
    appearance = "Appearance",
    darkMode = "Dark mode",
    lightMode = "Light mode",
    themeDescription = "Switch between dark and light theme",
    data = "Data",
    exportBackup = "Export backup",
    importBackup = "Import backup",
    exportData = "Export data",
    importData = "Import data",
    accounts = "Accounts",
    noAccounts = "No accounts",
    dangerZone = "Danger zone",
    dangerZoneDescription = "Destructive actions are isolated here and require confirmation.",
    deleteAllData = "Delete all data",
    language = "Language",
    settingsTabGeneral = "General",
    settingsTabAccounts = "Accounts",
    settingsTabData = "Data",
    settingsTabCloud = "Cloud",
    settingsTabAbout = "About",

    // Cloud sync
    cloudSync = "Cloud sync",
    cloudStatusConnected = "Connected",
    cloudStatusDisconnected = "Disconnected",
    cloudStatusConnecting = "Connecting",
    cloudStatusUploading = "Uploading",
    cloudStatusDownloading = "Downloading",
    cloudStatusConflict = "Conflict pending",
    cloudStatusReady = "Ready",
    connectDrive = "Connect Google Drive",
    disconnectDrive = "Disconnect",
    driveConnected = "Connected as %s",
    uploadNow = "Upload now",
    restoreFromDrive = "Restore from Drive",
    autoSync = "Auto-sync",
    manualSync = "Manual sync",
    autoSyncDescription = "Upload on close, download on launch",
    lastSync = "Last sync: %s",
    lastSyncNever = "Never synced",
    syncSuccess = "Synced with Google Drive",
    syncError = "Sync failed",
    syncing = "Syncing…",
    syncingToDrive = "Syncing to Google Drive…",
    confirmRestoreFromDrive = "Restore from Drive?",
    confirmRestoreFromDriveText = "All current data will be replaced with the Drive backup. This action cannot be undone.",
    cloudDiffTitle = "Cloud backup differs from local",
    cloudDiffSubtitle = "Your Google Drive backup is different from your local data. Choose which one to keep.",
    cloudDiffAccounts = "Accounts",
    cloudDiffTransactions = "Transactions",
    cloudDiffSnapshots = "Investment snapshots",
    cloudDiffEntity = "Data",
    cloudDiffAdded = "added",
    cloudDiffRemoved = "removed",
    cloudDiffModified = "modified",
    cloudBackupTimestamp = "Cloud backup: %s",
    localDataCurrent = "Local data: current device state",
    keepLocal = "Keep local",
    useCloud = "Use cloud",

    // Command palette
    commandPalette = "Command palette",
    commandPalettePlaceholder = "Search actions or accounts…",
    commandPaletteNoResults = "No matching actions",
    commandOpenAccount = "Open %s",
    commandNewTransaction = "New transaction",
    commandUpdateSnapshot = "Update investment value",
    commandFocusSearch = "Search transactions",
    commandReviewUncategorized = "Review uncategorized",

    // Import preview
    importPreviewTitle = "Preview backup import",
    importPreviewSubtitle = "Review the differences before replacing local data with this file.",
    importPreviewBackupTimestamp = "File backup: %s",
    importPreviewNoChanges = "No differences detected against local data",
    importPreviewRestore = "Restore file",

    // Confirm dialogs
    confirmDeleteTransaction = "Delete transaction?",
    confirmDeleteTransactionText = "This action cannot be undone.",
    confirmDeleteSnapshot = "Delete weekly record?",
    confirmDeleteSnapshotText = "This action cannot be undone.",
    confirmDeleteAccount = "Delete account?",
    confirmDeleteAccountText = "The account and all its transactions and snapshots will be permanently deleted. This action cannot be undone.",
    confirmDeleteAll = "Delete all data?",
    confirmDeleteAllText = "All accounts, transactions and snapshots will be deleted. The application will be empty. This action cannot be undone.",
    confirmDeleteAllTypedInstruction = "Type %s to permanently delete all local data.",
    confirmDeleteAllInputLabel = "Confirmation",
    confirmDeleteAllPhrase = "DELETE",
    deleteAll = "Delete all",
    confirmRestoreBackup = "Restore backup?",
    confirmRestoreBackupText = "All current data will be deleted and replaced with the file contents. This action cannot be undone.",
    restore = "Restore",
)
