package com.aracem.joyufy.ui.strings

object StringsEs : Strings {
    // Navigation
    override val goBack = "Volver"
    override val sidebarDashboard = "Dashboard"
    override val sidebarTransactions = "Transacciones"
    override val sidebarSettings = "Ajustes"
    override val sidebarCollapse = "Colapsar sidebar"
    override val sidebarExpand = "Expandir sidebar"
    override val sidebarReorderEnter = "Ordenar cuentas"
    override val sidebarReorderExit = "Salir del modo ordenar"
    override val sidebarReorder = "Reordenar"
    override val sidebarNewAccount = "Nueva cuenta"
    override val sidebarQuickAdd = "Añadir transacción"
    override val sidebarDarkMode = "Modo claro"
    override val sidebarLightMode = "Modo oscuro"

    // Common actions
    override val cancel = "Cancelar"
    override val delete = "Eliminar"
    override val edit = "Editar"
    override val saveChanges = "Guardar cambios"
    override val close = "Cerrar"
    override val download = "Descargar"
    override val undo = "Deshacer"
    override val selectAll = "Seleccionar todo"
    override val clearSelection = "Limpiar selección"

    // Dashboard
    override val totalWealth = "Patrimonio total"
    override val noAccountsYet = "Sin cuentas todavía"
    override val addFirstAccount = "Crea la primera cuenta y el dashboard empezará a seguir tu patrimonio automáticamente"
    override val createBankAccount = "Cuenta bancaria"
    override val createInvestmentAccount = "Cuenta de inversión"
    override val createCashAccount = "Cuenta de efectivo"
    override val evolution = "Evolución"
    override val changeView = "Cambiar vista"
    override val chartModeArea = "Área"
    override val chartModeBars = "Barras"
    override val chartVisibility = "Datos visibles"
    override val chartVisibilityAll = "Todo"
    override val chartVisibilityLiquid = "Solo líquido"
    override val chartVisibilityInvestments = "Solo inversión"
    override val chartVisibilityCustom = "Personalizado"
    override val composition = "Composición"
    override val compositionEmpty = "Aún no hay balances positivos"
    override val missingSnapshotTitle = "Actualización semanal de inversión pendiente"
    override val missingSnapshotSubtitle = "Actualiza las cuentas de inversión atrasadas antes de cerrar la semana"
    override val missingSnapshotLastValue = "Último valor: %s"
    override val missingSnapshotNever = "Sin actualizar"
    override val dashboardActions = "Por revisar"
    override val uncategorized = "Sin categoría"
    override val pendingSnapshots = "Snapshots pendientes"
    override val negativeBalances = "Balances negativos"
    override val hiddenSeries = "Series ocultas"
    override val periodComparison = "Comparativa"
    override val vsPreviousMonth = "vs mes anterior"
    override val analysis = "Análisis"
    override val collapse = "Colapsar"
    override val expand = "Expandir"

    // Monthly summary
    override val currentMonth = "Este mes"
    override val income = "Ingresos"
    override val expenses = "Gastos"
    override val investment = "Inversión"
    override val net = "Neto"
    override val topExpenses = "Top gastos"
    override val monthCurrent = "Mes actual"

    // Annual summary
    override val currentYear = "Este año"
    override val yearAll = "Todo"
    override val yearPrevious = "Año anterior"
    override val yearNext = "Año siguiente"

    // Chart ranges
    override val chartWeek = "1S"
    override val chartMonth = "1M"
    override val chartThreeMonths = "3M"
    override val chartSixMonths = "6M"
    override val chartYtd = "YTD"
    override val chartYear = "1A"
    override val rangeOneWeek = "en la última semana"
    override val rangeOneMonth = "en el último mes"
    override val rangeThreeMonths = "en los últimos 3 meses"
    override val rangeSixMonths = "en los últimos 6 meses"
    override val rangeYtd = "en lo que va de año"
    override val rangeOneYear = "en el último año"
    override val rangeAll = "desde el inicio"

    // Account detail
    override val confirmTypeChangeTitle = "¿Cambiar tipo de cuenta?"
    override val confirmTypeChangeBody = "Esta operación es destructiva y no se puede deshacer."
    override val confirmTypeChangeBankToInvestment = "Cambiar a Inversión eliminará %1\$d transacciones y las reemplazará por un único snapshot de esta semana con el balance actual."
    override val confirmTypeChangeInvestmentToBank = "Salir de Inversión eliminará %1\$d snapshots semanales. Las transacciones de la cuenta se conservarán."
    override val confirmTypeChangeContinue = "Cambiar tipo"
    override val editAccount = "Editar cuenta"
    override val updateValue = "Actualizar valor"
    override val addTransaction = "Añadir transacción"
    override val currentBalance = "Balance actual"
    override val transactions = "Transacciones"
    override val monthSubtotal = "Subtotal del mes"
    override val runningBalance = "Balance acumulado"
    override val noTransactions = "Aún no hay transacciones"
    override val noTransactionsHint = "Pulsa «Añadir transacción» para registrar la primera"
    override val noSearchResults = "Sin resultados"
    override val noSearchResultsHint = "Prueba a cambiar o limpiar los filtros"
    override val weeklyValue = "Valor de mercado semanal"
    override val noWeeklyRecords = "Sin registros semanales"
    override val noWeeklyRecordsHint = "Pulsa «Actualizar valor» para añadir el primero"
    override val editValue = "Editar valor"
    override val weekCurrent = "Semana actual — "
    override val week = "Semana"

    // Filters
    override val clearFilters = "Limpiar"
    override val searchDescriptionCategory = "Buscar por descripción o categoría…"
    override val transactionType = "Tipo"
    override val dateFrom = "Desde"
    override val dateTo = "Hasta"
    override val amountMin = "Mín."
    override val amountMax = "Máx."
    override val transfersOnly = "Solo transferencias"
    override val transferOut = "Transferencia →"
    override val transferIn = "Transferencia ←"

    // Add/Edit transaction
    override val editTransaction = "Editar transacción"
    override val newTransaction = "Nueva transacción"
    override val amountEur = "Importe (€)"
    override val dateFormat = "Fecha (dd/MM/aaaa)"
    override val categoryOptional = "Categoría (opcional)"
    override val descriptionOptional = "Descripción (opcional)"
    override val destinationAccount = "Cuenta destino"
    override val selectDate = "Seleccionar fecha"
    override val selectDestinationAccount = "Selecciona una cuenta destino para continuar"
    override val noDestinationAccounts = "Crea otra cuenta antes de registrar una transferencia"
    override val placeholderAmount = "0,00"
    override val buttonTransfer = "Transferir"
    override val buttonAdd = "Añadir"
    override val amountError = "Introduce un importe válido"
    override val dateError = "Usa el formato dd/MM/aaaa"
    override val transactionTemplates = "Plantillas"
    override val templateSalary = "Nómina"
    override val templateGroceries = "Supermercado"
    override val templateRent = "Alquiler"
    override val templateSubscription = "Suscripción"
    override val templateInvestmentTransfer = "Aporte inversión"

    // Add/Edit snapshot
    override val totalValueEur = "Valor total (€)"
    override val valueError = "Introduce un valor válido"
    override val save = "Guardar"

    // Create account
    override val newAccount = "Nueva cuenta"
    override val createAccount = "Crear cuenta"
    override val name = "Nombre"
    override val typeLabel = "Tipo"
    override val color = "Color"
    override val placeholderName = "Ej: Banco Santander"
    override val customColor = "Color personalizado"
    override val placeholderColor = "#7B6EF6"
    override val initialBalanceOptional = "Saldo inicial (opcional)"
    override val bankOrPlatform = "Banco o plataforma"
    override val moreOptions = "Más opciones"

    // Account types
    override val accountTypeBank = "Banco"
    override val accountTypeInvestment = "Inversión"
    override val accountTypeCash = "Efectivo"

    // Transaction types
    override val transactionIncome = "Ingreso"
    override val transactionExpense = "Gasto"
    override val transactionTransfer = "Transferencia"

    // Transaction ledger
    override val transactionLedger = "Libro de transacciones"
    override val ledgerSubtitle = "%d transacciones en todas las cuentas"
    override val ledgerReviewInbox = "Bandeja de revisión"
    override val ledgerAll = "Todo"
    override val ledgerDataQuality = "Calidad de datos"
    override val ledgerSearchPlaceholder = "Buscar transacciones, cuentas, categorías…"
    override val ledgerAllAccounts = "Todas las cuentas"
    override val ledgerAllTypes = "Todos los tipos"
    override val ledgerSelectedCount = "%d seleccionadas"
    override val ledgerBulkCategory = "Categoría"
    override val ledgerApplyCategory = "Aplicar categoría"
    override val ledgerMoveToAccount = "Mover cuenta"
    override val ledgerMarkReviewed = "Marcar revisadas"
    override val ledgerDeleteSelected = "Eliminar"
    override val ledgerDeletedTransactions = "%d transacciones eliminadas"
    override val ledgerRestoredTransactions = "%d transacciones restauradas"
    override val ledgerUpdatedTransactions = "%d transacciones actualizadas"
    override val ledgerNoTransactions = "No hay transacciones con estos filtros"
    override val ledgerDataQualityTitle = "Calidad de datos"
    override val ledgerMissingCategories = "Categorías vacías"
    override val ledgerEmptyDescriptions = "Descripciones vacías"
    override val ledgerPossibleDuplicates = "Posibles duplicados"
    override val ledgerBrokenTransfers = "Transferencias rotas"
    override val ledgerUnusualAmounts = "Importes inusuales"
    override val ledgerStaleAccounts = "Cuentas sin actividad"
    override val ledgerStaleSnapshots = "Snapshots atrasados"
    override val ledgerImportedDrafts = "Borradores importados"
    override val ledgerImportedDraft = "Borrador importado"
    override val ledgerMissingCategory = "Sin categoría"
    override val ledgerEmptyDescription = "Sin descripción"
    override val ledgerDuplicateHint = "Grupo duplicado: %d"
    override val ledgerBrokenTransfer = "Transferencia rota"
    override val ledgerUnusualAmount = "Importe inusual"
    override val ledgerNoDescription = "Sin descripción"

    // Settings
    override val settings = "Ajustes"
    override val appearance = "Apariencia"
    override val darkMode = "Modo oscuro"
    override val lightMode = "Modo claro"
    override val themeDescription = "Cambia entre tema oscuro y claro"
    override val data = "Datos"
    override val exportBackup = "Exportar backup"
    override val importBackup = "Importar backup"
    override val exportData = "Exportar datos"
    override val importData = "Importar datos"
    override val accounts = "Cuentas"
    override val noAccounts = "Sin cuentas"
    override val dangerZone = "Zona de peligro"
    override val dangerZoneDescription = "Las acciones destructivas están aisladas aquí y requieren confirmación."
    override val deleteAllData = "Borrar todos los datos"
    override val language = "Idioma"
    override val settingsTabGeneral = "General"
    override val settingsTabAccounts = "Cuentas"
    override val settingsTabData = "Datos"
    override val settingsTabCloud = "Nube"
    override val settingsTabAbout = "Acerca de"

    // Cloud sync
    override val cloudSync = "Sincronización en la nube"
    override val cloudStatusConnected = "Conectado"
    override val cloudStatusDisconnected = "Desconectado"
    override val cloudStatusConnecting = "Conectando"
    override val cloudStatusUploading = "Subiendo"
    override val cloudStatusDownloading = "Descargando"
    override val cloudStatusConflict = "Conflicto pendiente"
    override val cloudStatusReady = "Listo"
    override val connectDrive = "Conectar Google Drive"
    override val disconnectDrive = "Desconectar"
    override val driveConnected = "Conectado como %s"
    override val uploadNow = "Subir ahora"
    override val restoreFromDrive = "Restaurar desde Drive"
    override val autoSync = "Sync automático"
    override val manualSync = "Sync manual"
    override val autoSyncDescription = "Sube al cerrar, descarga al abrir"
    override val lastSync = "Última sync: %s"
    override val lastSyncNever = "Sin sincronizar"
    override val syncSuccess = "Sincronizado con Google Drive"
    override val syncError = "Error al sincronizar"
    override val syncing = "Sincronizando…"
    override val syncingToDrive = "Sincronizando con Google Drive…"
    override val confirmRestoreFromDrive = "¿Restaurar desde Drive?"
    override val confirmRestoreFromDriveText = "Todos los datos actuales se reemplazarán con el backup de Drive. Esta acción no se puede deshacer."
    override val cloudDiffTitle = "El backup en la nube difiere del local"
    override val cloudDiffSubtitle = "Tu backup en Google Drive es diferente a tus datos locales. Elige cuál quieres conservar."
    override val cloudDiffAccounts = "Cuentas"
    override val cloudDiffTransactions = "Transacciones"
    override val cloudDiffSnapshots = "Snapshots de inversión"
    override val cloudDiffEntity = "Datos"
    override val cloudDiffAdded = "añadidos"
    override val cloudDiffRemoved = "eliminados"
    override val cloudDiffModified = "modificados"
    override val cloudBackupTimestamp = "Backup en la nube: %s"
    override val localDataCurrent = "Datos locales: estado actual del dispositivo"
    override val keepLocal = "Mantener local"
    override val useCloud = "Usar nube"

    // Command palette
    override val commandPalette = "Paleta de comandos"
    override val commandPalettePlaceholder = "Busca acciones o cuentas…"
    override val commandPaletteNoResults = "No hay acciones que coincidan"
    override val commandOpenAccount = "Abrir %s"
    override val commandNewTransaction = "Nueva transacción"
    override val commandUpdateSnapshot = "Actualizar valor de inversión"
    override val commandFocusSearch = "Buscar transacciones"
    override val commandReviewUncategorized = "Revisar sin categoría"

    // Import preview
    override val importPreviewTitle = "Previsualizar importación"
    override val importPreviewSubtitle = "Revisa las diferencias antes de reemplazar los datos locales con este archivo."
    override val importPreviewBackupTimestamp = "Backup del archivo: %s"
    override val importPreviewNoChanges = "No hay diferencias respecto a los datos locales"
    override val importPreviewRestore = "Restaurar archivo"

    // CSV import
    override val csvImportTitle = "Importar extracto bancario"
    override val csvImportSubtitle = "Soporta CSV, TSV, OFX y exportaciones de texto de ING. Los duplicados se bloquean antes de importar."
    override val csvDefaultAccount = "Cuenta por defecto"
    override val csvImportRows = "%d filas"
    override val csvImportValid = "%d válidas"
    override val csvImportErrors = "%d errores"
    override val csvImportDuplicates = "%d duplicados"
    override val csvImportInvalidField = "%s inválido"
    override val csvImportDuplicateHint = "Duplicado: no se importará"
    override val csvImportCommit = "Importar %d"
    override val csvImportSuccess = "%d transacciones importadas como borradores"

    // Undo feedback
    override val snapshotDeleted = "Snapshot eliminado"
    override val accountDeleted = "%s eliminada"
    override val accountArchived = "%s archivada"
    override val accountRestored = "%s restaurada"

    // Confirm dialogs
    override val confirmDeleteTransaction = "¿Eliminar transacción?"
    override val confirmDeleteTransactionText = "Esta acción no se puede deshacer."
    override val confirmDeleteSnapshot = "¿Eliminar registro semanal?"
    override val confirmDeleteSnapshotText = "Esta acción no se puede deshacer."
    override val confirmDeleteAccount = "¿Eliminar cuenta?"
    override val confirmDeleteAccountText = "Se eliminarán permanentemente la cuenta y todas sus transacciones y snapshots. Esta acción no se puede deshacer."
    override val confirmDeleteAll = "¿Borrar todos los datos?"
    override val confirmDeleteAllText = "Se eliminarán todas las cuentas, transacciones y snapshots. La aplicación quedará vacía. Esta acción no se puede deshacer."
    override val confirmDeleteAllTypedInstruction = "Escribe %s para borrar permanentemente todos los datos locales."
    override val confirmDeleteAllInputLabel = "Confirmación"
    override val confirmDeleteAllPhrase = "BORRAR"
    override val deleteAll = "Borrar todo"
    override val confirmRestoreBackup = "¿Restaurar backup?"
    override val confirmRestoreBackupText = "Se borrarán todos los datos actuales y se reemplazarán con los del archivo. Esta acción no se puede deshacer."
    override val restore = "Restaurar"
}
